#!/usr/bin/env python3
"""
Convert data/raw/devices.xlsx to:
  - data/sql/SPL.sql  (plain SQL script)
  - data/SPL.db       (SQLite database)
Parses WKB hex-encoded geometry (EWKB with SRID) to extract lat/long.
"""

import struct
import sqlite3
import openpyxl
import os

INPUT_FILE = os.path.join(os.path.dirname(__file__), "../data/raw/devices.xlsx")
OUTPUT_SQL  = os.path.join(os.path.dirname(__file__), "../data/sql/SPL.sql")
OUTPUT_DB   = os.path.join(os.path.dirname(__file__), "../data/SPL.db")


def parse_wkb_point(hex_str):
    """Parse an EWKB hex string and return (longitude, latitude)."""
    data = bytes.fromhex(hex_str)
    byte_order = data[0]  # 1 = little-endian, 0 = big-endian
    endian = "<" if byte_order == 1 else ">"

    # wkb_type is at offset 1 (4 bytes); EWKB with SRID flag: 0x20000000
    wkb_type = struct.unpack_from(endian + "I", data, 1)[0]
    has_srid = bool(wkb_type & 0x20000000)

    coord_offset = 5 + (4 if has_srid else 0)
    lon, lat = struct.unpack_from(endian + "dd", data, coord_offset)
    return lat, lon


def escape_sql(value):
    if value is None:
        return "NULL"
    return "'" + str(value).replace("'", "''") + "'"


def main():
    os.makedirs(os.path.dirname(OUTPUT_SQL), exist_ok=True)
    os.makedirs(os.path.dirname(OUTPUT_DB), exist_ok=True)

    wb = openpyxl.load_workbook(INPUT_FILE)
    ws = wb.active

    headers = [cell.value for cell in ws[1]]
    print(f"Columns: {headers}")

    lower_headers = [str(h).lower() if h else "" for h in headers]

    def col(name):
        try:
            return lower_headers.index(name)
        except ValueError:
            return None

    id_col = col("id")
    name_col = col("name")
    loc_col = next(
        (i for i, h in enumerate(lower_headers) if "location" in h or "geom" in h or "wkb" in h),
        None,
    )

    if any(c is None for c in [id_col, name_col, loc_col]):
        raise ValueError(
            f"Could not find required columns. Found: {headers}\n"
            f"id={id_col}, name={name_col}, location={loc_col}"
        )

    # --- collect rows ---
    rows = []
    skipped = 0
    for row in ws.iter_rows(min_row=2, values_only=True):
        device_id = row[id_col]
        name = row[name_col]
        location = row[loc_col]

        if not location:
            skipped += 1
            continue

        try:
            lat, lon = parse_wkb_point(str(location).strip())
        except Exception as e:
            print(f"  [warn] Skipping row id={device_id}: {e}")
            skipped += 1
            continue

        rows.append((device_id, name, lat, lon))

    # --- write SQL file ---
    lines = [
        "-- Generated by scripts/xls_to_sql.py",
        "",
        "CREATE TABLE IF NOT EXISTS devices (",
        "    id      INTEGER PRIMARY KEY,",
        "    name    TEXT    NOT NULL,",
        "    lat     REAL    NOT NULL,",
        "    long    REAL    NOT NULL",
        ");",
        "",
    ]
    for device_id, name, lat, lon in rows:
        lines.append(
            f"INSERT INTO devices (id, name, lat, long) VALUES "
            f"({escape_sql(device_id)}, {escape_sql(name)}, {lat}, {lon});"
        )
    with open(OUTPUT_SQL, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print(f"SQL file: {OUTPUT_SQL}")

    # --- write SQLite DB ---
    if os.path.exists(OUTPUT_DB):
        os.remove(OUTPUT_DB)
    con = sqlite3.connect(OUTPUT_DB)
    cur = con.cursor()
    cur.execute("""
        CREATE TABLE devices (
            id      INTEGER PRIMARY KEY,
            name    TEXT    NOT NULL,
            lat     REAL    NOT NULL,
            long    REAL    NOT NULL
        )
    """)
    cur.executemany(
        "INSERT INTO devices (id, name, lat, long) VALUES (?, ?, ?, ?)", rows
    )
    con.commit()
    con.close()
    print(f"SQLite DB: {OUTPUT_DB}")

    print(f"Done. {len(rows)} rows inserted, {skipped} skipped.")


if __name__ == "__main__":
    main()
